development:

  clients:

    default:
      
      database: api1
      
      hosts:
        - localhost:27017
      options:

  options:
  
test:
  clients:
    default:
      database: api1_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
